services:
  - type: web
    name: pozitiv
    plan: free
    autoDeploy: false
    runtime: docker
    repo: https://github.com/raffi1300/hi.events-render.com.git
    region: virginia
    envVars:
      - key: PORT
        value: 80
      - key: DATABASE_URL
        fromDatabase:
          name: pozitiv-db
          property: connectionString
      - key: APP_KEY
        value: base64:G/ZFls3twiNLjiGrC0W2Zs475ZWxH4UsuvAV4u24wOE=
      - key: JWT_SECRET
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: array
      - key: FILESYSTEM_PUBLIC_DISK
        value: public
      - key: FILESYSTEM_PRIVATE_DISK
        value: local
databases:
  - name: pozitiv-db
    plan: free
    region: virginia
